# dataset_path: ./dataset
data_path: ./dataset/data
label_path: ./dataset/label/index
phase: full
alpha: 1
beta: 1
seed: 1
vocabulary_volume: 1000
word_model: tf-idf
content_feature: True
save_result: ./workdir/result_tf_idf_content_feature.txt